Global Firewall remediation
ScaleSec/project_lockdown pull request #38
Opened 2021-01-07 23:05 UTC by dgwhited

Remediates firewalls with 0.0.0.0/0 source ranges when created or modified.

Also adds a feature to set function memory independently because this function runs over 128mb after garbage collection and other trimming efforts.

2021-01-08 18:45 UTC, jdyke requested changes

2021-01-08 18:45 UTC, jdyke commented on src/public_firewall_port/main.py
> +def check_resource(project_id, firewall_name):
Can you add a docstring to this function?

2021-01-08 18:45 UTC, jdyke commented on src/public_firewall_port/main.py
> +    """ Gets information about the firewall
Should this description be inside the docstring?

2021-01-08 18:45 UTC, jdyke commented on src/public_firewall_port/main.py
> +        logging.info(f'Could not retrieve enablement status for {firewall_name}.')
`logging.error` vs `logging.info` ?

2021-01-08 18:45 UTC, jdyke commented on src/public_firewall_port/main.py
> +    """ Disables a firewall rule
ditto above description inside docstring

2021-01-08 18:45 UTC, jdyke commented on src/public_firewall_port/main.py
> +        logging.info(f'Could not disable firewall: {firewall_name}.')
`logging.error` vs `logging.info` ?

2021-01-08 21:43 UTC, dgwhited commented on src/public_firewall_port/main.py
> +        logging.info(f'Could not retrieve enablement status for {firewall_name}.')
good call

2021-01-09 18:34 UTC, jdyke approved these changes
LGTM, thanks for contributing this use case @dgwhited

2021-01-09 18:34 UTC, merged